import { Eth, SUI } from "../assets";

export const transactions = [
  {
    id: 1,
    amount: "0.9 ETH",
    name: "ETH",
    network: "Ethereum Mainnet",
    status: "Complete",
    hash: "0x93...7fE1",
    time: "4d 19h ago",
    action: "View",
    tokenIcon: Eth,
    aiStatus: "Verified",
    address: "0x93...7fE1",
  },
  {
    id: 2,
    amount: "6 SUI",
    name: "sui",
    network: "SUI Network",
    status: "Pending",
    hash: "0x93...7fE1",
    time: "4d 19h ago",
    action: "View",
    tokenIcon: SUI,
    aiStatus: "Verified",
    address: "0x93...7fE1",
  },
  {
    id: 3,
    amount: "12 SUI",
    name: "Sui",
    network: "SUI Network",
    status: "Warning",
    hash: "0x93...7fE1",
    time: "4d 19h ago",
    action: "Reversible",
    tokenIcon: SUI,
    aiStatus: "Warning Detected",
    address: "0x93...7fE1",
  },
  {
    id: 4,
    amount: "8 SUI",
    name: "Sui",
    network: "SUI Network",
    status: "Pending",
    hash: "0x93...7fE1",
    time: "4d 19h ago",
    action: "View",
    tokenIcon: SUI,
    aiStatus: "Verified",
    address: "0x93...7fE1",
  },
  {
    id: 5,
    amount: "8.5 ETH",
    name: "ETH",
    network: "Ethereum Mainnet",
    status: "Complete",
    hash: "0x93...7fE1",
    time: "4d 19h ago",
    action: "View",
    tokenIcon: Eth,
    aiStatus: "Verified",
    address: "0x93...7fE1",
  },
];
